### ISSUE TITLE
Bug: Upload failing

### ISSUE THREAD

**Issue by MalteMagnussen** [Forceu/Gokapi#189]
Updated the app to the latest version from main branch from version 1.8.4 

We upload to S3.

Seeing this issue after update (the upload never finishes):

![image](https://github.com/user-attachments/assets/7effd964-3e89-47a1-be1b-d61e3bcdbde9)

I submoduled this repo into "gokapi" folder, and building the image we're running like this:

```Dockerfile
FROM golang:1.22.3-alpine AS build_base

RUN mkdir /compile
COPY ./gokapi/go.mod /compile
RUN cd /compile && go mod download

COPY ./gokapi/ /compile
# Adding our own .css and an update to html tmpl for branding.
COPY ./web/ /compile/internal/webserver/web/

RUN cd /compile && go generate ./... && CGO_ENABLED=0 go build -ldflags="-s -w -X 'github.com/forceu/gokapi/internal/environment.IsDocker=true' -X 'github.com/forceu/gokapi/internal/environment.Builder=Project Docker File' -X 'github.com/forceu/gokapi/internal/environment.BuildTime=$(date)'" -o /compile/gokapi github.com/forceu/gokapi/cmd/gokapi

FROM alpine:3.19

RUN addgroup -S gokapi && adduser -S gokapi -G gokapi
RUN apk update && apk add --no-cache su-exec tini ca-certificates curl tzdata && mkdir /app && touch /app/.isdocker

COPY ./gokapi/dockerentry.sh /app/run.sh

COPY --from=build_base /compile/gokapi /app/gokapi
WORKDIR /app

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/app/run.sh"]
HEALTHCHECK --interval=10s --timeout=5s --retries=3 CMD curl --fail http://127.0.0.1:53842 || exit 1
```

Log output:

```bash
2024/07/12 14:29:11 http: panic serving 10.217.7.232:57516: constraint failed: NOT NULL constraint failed: UploadStatus.LastUpdate (1299)
goroutine 242 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1898 +0xbe
panic({0xdb8d00?, 0xc00063f4a0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/forceu/gokapi/internal/helper.Check(...)
        /compile/internal/helper/OS.go:63
github.com/forceu/gokapi/internal/configuration/database/provider/sqlite.DatabaseProvider.SaveUploadStatus({0xc000726066?}, {{0xc000726066, 0x24}, 0x0, {0x0, 0x0}})
        /compile/internal/configuration/database/provider/sqlite/uploadstatus.go:71 +0x156
github.com/forceu/gokapi/internal/configuration/database.SaveUploadStatus(...)
        /compile/internal/configuration/database/Database.go:262
github.com/forceu/gokapi/internal/storage/processingstatus.Set({0xc000726066?, 0xc00060edb0?}, 0x26?)
        /compile/internal/storage/processingstatus/ProcessingStatus.go:33 +0x165
github.com/forceu/gokapi/internal/storage.NewFileFromChunk({_, _}, {{_, _}, {_, _}, _}, {0x5, 0xe, 0x66a3b2b7, ...})
        /compile/internal/storage/FileServing.go:141 +0x145
github.com/forceu/gokapi/internal/webserver/fileupload.CompleteChunk({0x2ca6c18, 0xc0005dc7e0}, 0xc000575200, 0x0)
        /compile/internal/webserver/fileupload/FileUpload.go:81 +0x234
github.com/forceu/gokapi/internal/webserver.uploadComplete({0x2ca6c18, 0xc0005dc7e0}, 0xc000575200)
        /compile/internal/webserver/Webserver.go:679 +0xda
net/http.HandlerFunc.ServeHTTP(0x2ca6c18?, {0x2ca6c18?, 0xc0005dc7e0?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2166 +0x29
github.com/forceu/gokapi/internal/webserver.Start.requireLogin.func10({0x2ca6c18, 0xc0005dc7e0}, 0xc000575200)
        /compile/internal/webserver/Webserver.go:736 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc00045d790?, {0x2ca6c18?, 0xc0005dc7e0?}, 0x10?)
        /usr/local/go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x411f65?, {0x2ca6c18, 0xc0005dc7e0}, 0xc000575200)
        /usr/local/go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0x2ca3810?}, {0x2ca6c18?, 0xc0005dc7e0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000200b40, {0x2ca74c8, 0xc000588ba0})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 44
        /usr/local/go/src/net/http/server.go:3285 +0x4b4
```

This is the config.json

```json
{
  "Authentication": {
    "Method": 1,
    "SaltAdmin": "redacted",
    "SaltFiles": "redacted",
    "Username": "",
    "Password": "",
    "HeaderKey": "",
    "OauthProvider": "https://login.microsoftonline.com/redacted/v2.0",
    "OAuthClientId": "redacted",
    "OAuthClientSecret": "redacted",
    "OauthUserScope": "",
    "OauthGroupScope": "",
    "OAuthRecheckInterval": 24,
    "HeaderUsers": null,
    "OAuthGroups": [],
    "OauthUsers": []
  },
  "Port": ":53842",
  "ServerUrl": "https://redacted.com/",
  "RedirectUrl": "https://www.redacted.com",
  "PublicName": "redacted",
  "DataDir": "data",
  "DatabaseUrl": "sqlite://./data/gokapi.sqlite",
  "ConfigVersion": 21,
  "LengthId": 15,
  "MaxMemory": 50,
  "UseSsl": false,
  "MaxFileSizeMB": 102400,
  "ChunkSize": 45,
  "MaxParallelUploads": 4,
  "Encryption": {
    "Level": 0,
    "Cipher": null,
    "Salt": "",
    "Checksum": "",
    "ChecksumSalt": ""
  },
  "PicturesAlwaysLocal": false,
  "SaveIp": true,
  "IncludeFilename": false
}
```

Submodule revision

![image](https://github.com/user-attachments/assets/c53cba12-3197-4b55-ba87-c972ec661eaa)

If I run it locally in docker-compose, I can upload with a cloud config. 

**Pure guesswork and speculation:** maybe this has to do with an sqlite created on 1.8.4 not properly migrating to the latest commit? We use "Litestream" to persist the sqlite in our test and prod environment.

**Comment by MalteMagnussen** [comment]
I'll try to enter the running pod and remove the sqlite and see what happens.

**Comment by Forceu** [comment]
Thanks for the feedback! As you are using the current unstable version and your config file is correct for the version, Gokapi expects the database to be created from that version as well. I assume your Litestream instance is indeed loading an older DB.
This is an interesting edge case - at the moment the database is only upgraded, if Gokapi a new Gokapi version is detected. As the user can however choose a different (or old) database location / provider with the current version, this case might happen during normal use.

**Comment by Forceu** [comment]
There was a bug in the SQLite upgrade process, thanks for reporting it! Fixed in e0741c8

**Comment by MalteMagnussen** [comment]
@Forceu - Cleaned out the S3 bucket (and the SQLite backup) and restarted the Deployment. 

Working fine now. Will upgrade to newest sha, and see if upgrade works in "prod" (not released to users yet, so kinda still a test env)

Thanks for fixing the issue, and hope you had a nice weekend.

**Comment by Forceu** [comment]
Thank you, same to you!
